### ISSUE TITLE
New Topic: Intro

### ISSUE THREAD

**Issue by ungoldman** [codeforscience/webdata#2]
How about **Introduction to Numeric Computing and Data Science on the Web**? A lot of these topics have a steep learning curve for the uninitiated. Webdata 101?

**Comment by max-mapper** [comment]
excellent idea :) ill try to summarize here. I'm currently trying to fill out the initial topics each with their own summaries, then ill summarize the summaries

**Comment by ungoldman** [comment]
:+1: Looking forward to it, this is a great idea

**Comment by kgryte** [comment]
@ngoldman within the context of JavaScript (and Node.js), probably a bit early for a true Webdata 101 course. Many numeric computing tools are still in their infancy and under active development, preventing a meaningful introduction.

I and others have been working to build these tools (https://github.com/compute-io, https://github.com/dstructs/matrix, https://github.com/flow-io, https://github.com/distributions-io) and, once some APIs have settled, definitely have on the roadmap a comprehensive introduction/tutorial for using JS for numeric computing and data science.

**Comment by max-mapper** [comment]
I did a high level intro to data science in general: https://github.com/codeforscience/webdata/blob/master/README.md#introduction, I think anything more specific than that should live in one of these discussion issues

**Comment by ungoldman** [comment]
super cool :sunglasses: :cool: :+1:
